(in-package :cblas)

(define-foreign-library libcblas
  (:darwin (:or "/opt/homebrew/opt/openblas/lib/libopenblas.dylib"))
  (:unix   (:or "libcblas.so.3" "libcblas.so"))
  (t       (:default "libcblas")))

(use-foreign-library libcblas)

(defctype cblas-int :int)
(defctype cblas-index :size)
(defcenum (cblas-layout cblas-int)
  (:row-major 101)
  :col-major)
(defcenum (cblas-transpose cblas-int)
  (:no-trans 111)
  :trans
  :conj-trans)
(defcenum (cblas-uplo cblas-int)
  (:upper 121)
  :lower)
(defcenum (cblas-diag cblas-int)
  (:non-unit 131)
  :unit)
(defcenum (cblas-side cblas-int)
  (:left 141)
  :right)

(define-foreign-type cblas-buffer-type () ()
  (:actual-type :pointer))

(define-parse-method cblas-buffer ()
  (make-instance 'cblas-buffer-type))

(defmethod translate-to-foreign (value (type cblas-buffer-type))
  (cond ((pointerp value) value)
		(t (slot-value value 'buffer))))

(define-foreign-type cblas-complex-float-type () ()
  (:actual-type :pointer))

(define-parse-method cblas-complex-float ()
  (make-instance 'cblas-complex-float-type))

(defmethod cffi:expand-to-foreign-dyn (value var body (type cblas-complex-float-type))
  (let ((val (gensym "VAL")))
    `(let ((,val ,value))
       (cffi:with-foreign-object (,var :float 2)
         (setf (cffi:mem-aref ,var :float 0) (realpart ,val)
               (cffi:mem-aref ,var :float 1) (imagpart ,val))
         ,@body))))

(define-foreign-type cblas-complex-double-type () ()
  (:actual-type :pointer))

(define-parse-method cblas-complex-double ()
  (make-instance 'cblas-complex-double-type))

(defmethod cffi:expand-to-foreign-dyn (value var body (type cblas-complex-double-type))
  (let ((val (gensym "VAL")))
    `(let ((,val ,value))
       (cffi:with-foreign-object (,var :double 2)
         (setf (cffi:mem-aref ,var :double 0) (realpart ,val)
               (cffi:mem-aref ,var :double 1) (imagpart ,val))
         ,@body))))

(defcblasfun ("cblas_~aaxpy" ("s" "d" "c" "z")) :void
  (n     cblas-int)
  (alpha :scalar)
  (x     cblas-buffer)
  (incx  cblas-int)
  (y     cblas-buffer)
  (incy  cblas-int))

(defcblasfun ("cblas_~ascal" ("s" "d" "c" "z" "cs" "zd")) :void
  (n     cblas-int)
  (alpha :scalar)
  (x     cblas-buffer)
  (incx  cblas-int))

(defcblasfun ("cblas_~acopy" ("s" "d" "c" "z")) :void
  (n    cblas-int)
  (x    cblas-buffer)
  (incx cblas-int)
  (y    cblas-buffer)
  (incy cblas-int))

(defcblasfun ("cblas_~aswap" ("s" "d" "c" "z")) :void
  (n    cblas-int)
  (x    cblas-buffer)
  (incx cblas-int)
  (y    cblas-buffer)
  (incy cblas-int))

(defcblasfun ("cblas_~adot" ("s" "d")) :scalar
  (n    cblas-int)
  (x    cblas-buffer)
  (incx cblas-int)
  (y    cblas-buffer)
  (incy cblas-int))

(defcblasfun ("cblas_~adotu_sub" ("c" "z")) :void
  (n    cblas-int)
  (x    cblas-buffer)
  (incx cblas-int)
  (y    cblas-buffer)
  (incy cblas-int)
  (dotu :pointer))

(defcblasfun ("cblas_~adotc_sub" ("c" "z")) :void
  (n    cblas-int)
  (x    cblas-buffer)
  (incx cblas-int)
  (y    cblas-buffer)
  (incy cblas-int)
  (dotc :pointer))

(defcblasfun ("cblas_~anrm2" ("s" "d" "sc" "dz")) :scalar
  (n    cblas-int)
  (x    cblas-buffer)
  (incx cblas-int))

(defcblasfun ("cblas_~aasum" ("s" "d")) :scalar
  (n    cblas-int)
  (x    cblas-buffer)
  (incx cblas-int))

(defcblasfun ("cblas_i~aamax" ("s" "d" "c" "z")) cblas-index
  (n    cblas-int)
  (x    cblas-buffer)
  (incx cblas-int))

(defcblasfun ("cblas_~arotg" ("s" "d" "c" "z")) :void
  (a :pointer)
  (b :pointer)
  (c :pointer)
  (s :pointer))

(defcblasfun ("cblas_~arot" ("s" "d" "c" "z")) :void
  (n    cblas-int)
  (x    :pointer)
  (incx cblas-int)
  (y    :pointer)
  (incy cblas-int)
  (c    :scalar)
  (s    :scalar))

(defcblasfun ("cblas_~arotmg" ("s" "d")) :void
  (d1 :pointer)
  (d2 :pointer)
  (b1 :pointer)
  (b2 :scalar)
  (p  :pointer))

(defcblasfun ("cblas_~arotm" ("s" "d")) :void
  (n    cblas-int)
  (x    :pointer)
  (incx cblas-int)
  (y    :pointer)
  (p    :pointer))

(defcblasfun ("cblas_~agemv" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (trans  cblas-transpose)
  (m      cblas-int)
  (n      cblas-int)
  (alpha  :scalar)
  (a      cblas-buffer)
  (lda    cblas-int)
  (x      cblas-buffer)
  (incx   cblas-int)
  (beta   :scalar)
  (y      cblas-buffer)
  (incy   cblas-int))

(defcblasfun ("cblas_~ahemv" ("c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (x      :pointer)
  (incx   cblas-int)
  (beta   :scalar)
  (y      :pointer)
  (incy   cblas-int))

(defcblasfun ("cblas_~asymv" ("s" "d")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (x      :pointer)
  (incx   cblas-int)
  (beta   :scalar)
  (y      :pointer)
  (incy   cblas-int))

(defcblasfun ("cblas_~atrmv" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (trans  cblas-transpose)
  (diag   cblas-diag)
  (n      cblas-int)
  (a      :pointer)
  (lda    cblas-int)
  (x      :pointer)
  (incx   cblas-int))

(defcblasfun ("cblas_~atrsv" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (trans  cblas-transpose)
  (diag   cblas-diag)
  (n      cblas-int)
  (a      :pointer)
  (lda    cblas-int)
  (x      :pointer)
  (incx   cblas-int))

(defcblasfun ("cblas_~ager" ("s" "d")) :void
  (layout cblas-layout)
  (m      cblas-int)
  (n      cblas-int)
  (alpha  :scalar)
  (x      cblas-buffer)
  (incx   cblas-int)
  (y      cblas-buffer)
  (incy   cblas-int)
  (a      cblas-buffer)
  (lda    cblas-int))

(defcblasfun ("cblas_~ageru" ("c" "z")) :void
  (layout cblas-layout)
  (m      cblas-int)
  (n      cblas-int)
  (alpha  :scalar)
  (x      cblas-buffer)
  (incx   cblas-int)
  (y      cblas-buffer)
  (incy   cblas-int)
  (a      cblas-buffer)
  (lda    cblas-int))

(defcblasfun ("cblas_~agerc" ("c" "z")) :void
  (layout cblas-layout)
  (m      cblas-int)
  (n      cblas-int)
  (alpha  :scalar)
  (x      cblas-buffer)
  (incx   cblas-int)
  (y      cblas-buffer)
  (incy   cblas-int)
  (a      cblas-buffer)
  (lda    cblas-int))

(defcblasfun ("cblas_~asyr" ("s" "d")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :real)
  (x      :pointer)
  (incx   cblas-int)
  (a      :pointer)
  (lda    cblas-int))

(defcblasfun ("cblas_~aher" ("c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :real)
  (x      :pointer)
  (incx   cblas-int)
  (a      :pointer)
  (lda    cblas-int))

(defcblasfun ("cblas_~asyr2" ("s" "d")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :scalar)
  (x      :pointer)
  (incx   cblas-int)
  (y      :pointer)
  (incy   cblas-int)
  (a      :pointer)
  (lda    cblas-int))

(defcblasfun ("cblas_~aher2" ("c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :scalar)
  (x      :pointer)
  (incx   cblas-int)
  (y      :pointer)
  (incy   cblas-int)
  (a      :pointer)
  (lda    cblas-int))

(defcblasfun ("cblas_~ahpmv" ("c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :scalar)
  (ap     :pointer)
  (x      :pointer)
  (incx   cblas-int)
  (beta   :scalar)
  (y      :pointer)
  (incy   cblas-int))

(defcblasfun ("cblas_~aspmv" ("s" "d")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :scalar)
  (ap     :pointer)
  (x      :pointer)
  (incx   cblas-int)
  (beta   :scalar)
  (y      :pointer)
  (incy   cblas-int))

(defcblasfun ("cblas_~atpmv" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (trans  cblas-transpose)
  (diag   cblas-diag)
  (n      cblas-int)
  (ap     :pointer)
  (x      :pointer)
  (incx   cblas-int))

(defcblasfun ("cblas_~atpsv" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (trans  cblas-transpose)
  (diag   cblas-diag)
  (n      cblas-int)
  (ap     :pointer)
  (x      :pointer)
  (incx   cblas-int))

(defcblasfun ("cblas_~aspr" ("s" "d")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :real)
  (x      :pointer)
  (incx   cblas-int)
  (ap     :pointer))

(defcblasfun ("cblas_~ahpr" ("c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :real)
  (x      :pointer)
  (incx   cblas-int)
  (ap     :pointer))

(defcblasfun ("cblas_~aspr2" ("s" "d")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :scalar)
  (x      :pointer)
  (incx   cblas-int)
  (y      :pointer)
  (incy   cblas-int)
  (a      :pointer))

(defcblasfun ("cblas_~ahpr2" ("c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (n      cblas-int)
  (alpha  :scalar)
  (x      :pointer)
  (incx   cblas-int)
  (y      :pointer)
  (incy   cblas-int)
  (ap     :pointer))

(defcblasfun ("cblas_~agemm" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (transa cblas-transpose)
  (transb cblas-transpose)
  (m      cblas-int)
  (n      cblas-int)
  (k      cblas-int)
  (alpha  :scalar)
  (a      cblas-buffer)
  (lda    cblas-int)
  (b      cblas-buffer)
  (ldb    cblas-int)
  (beta   :scalar)
  (c      cblas-buffer)
  (ldc    cblas-int))

(defcblasfun ("cblas_~agemmtr" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (transa cblas-transpose)
  (transb cblas-transpose)
  (m      cblas-int)
  (n      cblas-int)
  (k      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (b      :pointer)
  (ldb    cblas-int)
  (beta   :scalar)
  (c      :pointer)
  (ldc    cblas-int))

(defcblasfun ("cblas_~asymm" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (side   cblas-side)
  (uplo   cblas-uplo)
  (m      cblas-int)
  (n      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (b      :pointer)
  (ldb    cblas-int)
  (beta   :scalar)
  (c      :pointer)
  (ldc    cblas-int))

(defcblasfun ("cblas_~ahemm" ("c" "z")) :void
  (layout cblas-layout)
  (side   cblas-side)
  (uplo   cblas-uplo)
  (m      cblas-int)
  (n      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (b      :pointer)
  (ldb    cblas-int)
  (beta   :scalar)
  (c      :pointer)
  (ldc    cblas-int))

(defcblasfun ("cblas_~atrmm" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (side   cblas-side)
  (uplo   cblas-uplo)
  (transa cblas-transpose)
  (diag   cblas-diag)
  (m      cblas-int)
  (n      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (b      :pointer)
  (ldb    cblas-int))

(defcblasfun ("cblas_~atrsm" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (side   cblas-side)
  (uplo   cblas-uplo)
  (transa cblas-transpose)
  (diag   cblas-diag)
  (m      cblas-int)
  (n      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (b      :pointer)
  (ldb    cblas-int))

(defcblasfun ("cblas_~asyrk" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (trans  cblas-transpose)
  (n      cblas-int)
  (k      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (beta   :scalar)
  (c      :pointer)
  (ldc    cblas-int))

(defcblasfun ("cblas_~aherk" ("c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (trans  cblas-transpose)
  (n      cblas-int)
  (k      cblas-int)
  (alpha  :real)
  (a      :pointer)
  (lda    cblas-int)
  (beta   :real)
  (c      :pointer)
  (ldc    cblas-int))

(defcblasfun ("cblas_~asyr2k" ("s" "d" "c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (trans  cblas-transpose)
  (n      cblas-int)
  (k      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (b      :pointer)
  (ldb    cblas-int)
  (beta   :scalar)
  (c      :pointer)
  (ldc    cblas-int))

(defcblasfun ("cblas_~aher2k" ("c" "z")) :void
  (layout cblas-layout)
  (uplo   cblas-uplo)
  (trans  cblas-transpose)
  (n      cblas-int)
  (k      cblas-int)
  (alpha  :scalar)
  (a      :pointer)
  (lda    cblas-int)
  (b      :pointer)
  (ldb    cblas-int)
  (beta   :real)
  (c      :pointer)
  (ldc    cblas-int))
