

(defun print-foreign-array (array type n)
  (dotimes (i n)
	(format t "  ~a~%" (mem-aref array type i))))

(with-foreign-objects ((vec-a :double 2)
					   (vec-b :double 2))
  (setf (mem-aref vec-a :double 0) 1.0d0)
  (setf (mem-aref vec-a :double 1) 1.0d0)
  (setf (mem-aref vec-b :double 0) 1.0d0)
  (setf (mem-aref vec-b :double 1) 1.0d0)


  (let ((a (make-instance 'cblas-zbuffer :buffer vec-a))
		(b (make-instance 'cblas-zbuffer :buffer vec-b)))
	(format t "Before vec-b~%")
	(print-foreign-array vec-b :double 2)
	(blas:axpy 1 (complex 1.0d0 1.0d0) a 1 b 1)
	(format t "After vec-b~%")
	(print-foreign-array vec-b :double 2)))
  

(with-foreign-objects ((vec-a :float 2)
					   (vec-b :float 2)
					   (mat-a :float 4)
					   (mat-b :float 4)
					   (mat-c :float 4))
  (setf (mem-aref vec-a :float 0) 1.0)
  (setf (mem-aref vec-a :float 1) 0.0)
  (setf (mem-aref vec-b :float 0) 0.0)
  (setf (mem-aref vec-b :float 1) 0.0)
  (setf (mem-aref mat-a :float 0) 1.0)
  (setf (mem-aref mat-a :float 1) 0.5)
  (setf (mem-aref mat-a :float 2) 0.1)
  (setf (mem-aref mat-a :float 3) 1.0)
  (setf (mem-aref mat-b :float 0) 3.4)
  (setf (mem-aref mat-b :float 1) 4.2)
  (setf (mem-aref mat-b :float 2) 2.3)
  (setf (mem-aref mat-b :float 3) 6.5)
  (setf (mem-aref mat-c :float 0) 0.0)
  (setf (mem-aref mat-c :float 1) 0.0)
  (setf (mem-aref mat-c :float 2) 0.0)
  (setf (mem-aref mat-c :float 3) 0.0)


  (let ((a (make-instance 'cblas-sbuffer :buffer vec-a))
		(b (make-instance 'cblas-sbuffer :buffer vec-b))
		(ma (make-instance 'cblas-sbuffer :buffer mat-a))
		(mb (make-instance 'cblas-sbuffer :buffer mat-b))
		(mc (make-instance 'cblas-sbuffer :buffer mat-c)))
	(format t "Before mat-c~%")
	(print-foreign-array mat-a :float 4)
	(print-foreign-array mat-b :float 4)
	(print-foreign-array mat-c :float 4)
	;(blas:axpy 1 (complex 1.0 1.0) a 1 b 1)
	;(blas:scal 1 (complex 1.0 0.0) b 1)
	;(blas:copy 1 a 1 b 1)
	(blas:gemm :no-trans :no-trans 2 2 2 1.0 ma 2 mb 2 0.0 mc 2)
	(format t "After mat-c~%")
	(print-foreign-array mat-c :float 4)))
